name: CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run test-lint
        env:
          CI: true

      - name: Lint CSS
        run: npm run test-lint-css
        env:
          CI: true

      - name: Lint HTML
        run: npm run test-lint-html
        env:
          CI: true

      - name: Tests
        run: npm run test-code
        env:
          CI: true

      - name: Manifest
        run: npm run test-manifest
        env:
          CI: true

      - name: Validate manifest.json of the extension
        uses: cardinalby/schema-validator-action@8407573c2627c5159428cf9fa3770d13b2360a27 # pin@v1
        with:
          file: ext/manifest.json
          schema: "https://json.schemastore.org/chrome-manifest.json"

      - name: Build
        run: npm run test-build
